
-- CREATE TABLE POKE_USER (
--     ID         VARCHAR2(24)  NOT NULL,
--     EMAIL      VARCHAR2(100) NOT NULL,
--     PASSWORD   VARCHAR2(255) NOT NULL,
--     NAME       VARCHAR2(50)  NOT NULL,
--     CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

--     CONSTRAINT PK_POKE_USER PRIMARY KEY (ID),
--     CONSTRAINT UK_POKE_USER_EMAIL UNIQUE (EMAIL)
-- );

-- -- ============================================================
-- -- SHOP / Poke_shops
-- -- ============================================================
CREATE TABLE POKE_NEWS (
    ID          NUMBER(19)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NEWS_ID     NUMBER(10),
    NEWS_TITLE  VARCHAR2(500),
    NEWS_IMG    VARCHAR2(1000),
    NEWS_URL    VARCHAR2(1000),
    NEWS_TYPE   VARCHAR2(100),
    NEWS_DATE   DATE
);

-- -- ============================================================
-- -- REVIEW / Poke_reviews
-- -- USER 1명은 REVIEW 여러 개 작성 가능
-- -- SHOP 1개는 REVIEW 여러 개 받을 수 있음
-- -- ============================================================
-- CREATE TABLE POKE_REVIEWS (
--     REVIEW_ID  VARCHAR2(24) NOT NULL,
--     USER_ID    VARCHAR2(24) NOT NULL,
--     SHOP_ID    VARCHAR2(24) NOT NULL,
--     CONTENT    CLOB,
--     RATING     NUMBER(1)    NOT NULL,
--     CREATED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,

--     CONSTRAINT PK_POKE_REVIEWS PRIMARY KEY (REVIEW_ID),
--     CONSTRAINT FK_POKE_REVIEWS_USER FOREIGN KEY (USER_ID)
--         REFERENCES POKE_USER (ID) ON DELETE CASCADE,
--     CONSTRAINT FK_POKE_REVIEWS_SHOP FOREIGN KEY (SHOP_ID)
--         REFERENCES POKE_SHOPS (SHOP_ID) ON DELETE CASCADE,
--     CONSTRAINT CK_POKE_REVIEWS_RATING CHECK (RATING BETWEEN 1 AND 5)
-- );

-- -- ============================================================
-- -- pokemon_news / Poke_news
-- -- ============================================================
-- CREATE TABLE POKE_NEWS (
--     NEWS_ID       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
--     NEWS_URL      VARCHAR2(500),
--     NEWS_TITLE    VARCHAR2(500) NOT NULL,
--     NEWS_TYPE     VARCHAR2(50),
--     NEWS_DATETIME TIMESTAMP,

--     CONSTRAINT PK_POKE_NEWS PRIMARY KEY (NEWS_ID)
-- );

-- -- ============================================================
-- -- pokemon_goods / Poke_goods
-- -- ============================================================
-- CREATE TABLE POKE_GOODS (
--     GOODS_ID       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
--     GOODS_URL      VARCHAR2(500),
--     GOODS_TITLE    VARCHAR2(500) NOT NULL,
--     GOODS_TYPE     VARCHAR2(50),
--     GOODS_DATETIME TIMESTAMP,

--     CONSTRAINT PK_POKE_GOODS PRIMARY KEY (GOODS_ID)
-- );

-- -- ============================================================
-- -- MBTI / Poke_mbti
-- -- ============================================================
-- CREATE TABLE POKE_MBTI (
--     MBTI_ID   NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
--     MBTI_CODE CHAR(4)    NOT NULL,

--     CONSTRAINT PK_POKE_MBTI PRIMARY KEY (MBTI_ID),
--     CONSTRAINT UK_POKE_MBTI_CODE UNIQUE (MBTI_CODE)
-- );

-- -- ============================================================
-- -- Character / Poke_npc
-- -- ============================================================
-- CREATE TABLE POKE_NPC (
--     CHAR_ID          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
--     CHAR_NAME        VARCHAR2(50)  NOT NULL,
--     CHAR_COLOR       VARCHAR2(90),
--     CHAR_DESCRIPTION VARCHAR2(255),

--     CONSTRAINT PK_POKE_NPC PRIMARY KEY (CHAR_ID)
-- );

-- -- ============================================================
-- -- Pokemon / Poke_dex
-- -- ============================================================
-- CREATE TABLE POKE_DEX (
--     DEX_ID          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
--     DEX_IMG         VARCHAR2(500),
--     DEX_ELEMENT     VARCHAR2(50),
--     DEX_HEIGHT      NUMBER(5,1),
--     DEX_WEIGHT      NUMBER(6,1),
--     DEX_TYPE        VARCHAR2(50),
--     DEX_DESCRIPTION VARCHAR2(500),

--     CONSTRAINT PK_POKE_DEX PRIMARY KEY (DEX_ID)
-- );

-- COMMIT;

-- -- 확인용
-- PROMPT ==============================
-- PROMPT Created tables in POKE schema:
-- PROMPT ==============================
-- SELECT TABLE_NAME
-- FROM USER_TABLES
-- WHERE TABLE_NAME LIKE 'POKE_%'
-- ORDER BY TABLE_NAME;
