# spring:
#   application:
#     name: server
#   datasource:
#     url: jdbc:oracle:thin:@192.168.0.51:9000/XEPDB1
#     # 51는 와이파이 5번 66은 4번
#     username: system
#     password: 1234
#     hikari:
#       connection-timeout: 5000
#       initialization-fail-timeout: 1  # 시작 시 연결 실패하면 바로 에러 출력

server:
  port: 8080  

spring:
  application:
    name: server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 5000
      initialization-fail-timeout: 1

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true